services:
  db:
    image: mariadb:10.11
    container_name: omron_mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      TZ: Asia/Tokyo
    # 外部(ホスト)からのアクセスを遮断し、内部ネットワーク内でのみ通信
    networks:
      - hems-omron
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # バッチ実行用のコンテナ
  batch:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: hems-batch:latest
    container_name: omron_batch
    environment:
      DB_DSN: "${MARIADB_USER}:${MARIADB_PASSWORD}@tcp(db:3306)/${MARIADB_DATABASE}?parseTime=true"
      OMRON_IP: "${OMRON_IP}"
      OMRON_DEVICE_ID: "${OMRON_DEVICE_ID}"
      TZ: Asia/Tokyo
    networks:
      - hems-omron
    depends_on:
      - db

  # 可視化ツール Grafana
  grafana:
    image: grafana/grafana-oss:latest
    container_name: omron_grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - TZ=Asia/Tokyo
    networks:
      - hems-omron
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - db

networks:
  hems-omron:
    driver: bridge

volumes:
  db_data:
  grafana_data:
